# Generated by Django 2.1.7 on 2019-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0006_auto_20190308_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceincents',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
