# Generated by Django 2.1.7 on 2019-03-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0007_auto_20190308_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
